default: &default
  adapter: postgresql
  username: admin
  password: admin
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: r_packager_d

test:
  <<: *default
  database: r_packager_t
