# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3f64ad67a2279bf1930c8b840a81fe361a28e98930c9e23fb514a247870fca53fc5d2ec4010c6f6e1c3e40eb45dc411a77d173d1d927614932416c0fce3dc6d

test:
  secret_key_base: b67d59f1a9b977470749c46c73fc4cc8056c3c09975b980601ac169d920dc0071800d673981d8552951be0916a353b83a504139233139ecb711fd34b894ff1d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
